import * as fs from "fs";
import * as path from "path";
import { WorkflowContext } from "./context.js";
import { Pipeline } from "./pipeline.js";
import { WorkflowExecutor } from "./executor.js";
import { PipelineStep } from "./step.js";
import { TemplateEngine } from "../templates/engine.js";
import { PluginManager } from "../plugins/manager.js";
import { Logger } from "../core/logger.js";

const supportedTemplates = ["agent", "website", "saas", "bim"];

export class WorkflowEngine {
  private steps: PipelineStep[];
  private pipeline: Pipeline;
  private executor: WorkflowExecutor;

  constructor() {
    this.steps = [
      new ValidateStep(),
      new LoadConfigStep(),
      new LoadPluginsStep(),
      new LoadTemplateStep(),
      new GenerateFilesStep(),
      new ReplaceVariablesStep(),
      new ValidateOutputStep(),
      new SuccessStep()
    ];
    this.pipeline = new Pipeline(this.steps);
    this.executor = new WorkflowExecutor(this.pipeline);
  }

  async execute(config: { commandName: string; args: string[] }) {
    const context = new WorkflowContext({
      commandName: config.commandName,
      args: config.args,
      templateRoot: path.resolve(process.cwd(), "templates"),
      projectRoot: path.resolve(process.cwd(), "projects"),
      pluginRoot: path.resolve(process.cwd(), "plugins"),
      configRoot: path.resolve(process.cwd(), "config")
    });

    return this.executor.run(context);
  }
}

class ValidateStep implements PipelineStep {
  name = "Validate";

  before() {
    Logger.info("Validating workflow inputs");
  }

  execute(context: WorkflowContext) {
    const [templateType, projectName] = context.config.args;
    if (!templateType || !projectName) {
      throw new Error("Usage: new <template> <project-name>");
    }

    if (!supportedTemplates.includes(templateType)) {
      throw new Error(`Unsupported template: ${templateType}`);
    }

    context.state.templateName = templateType;
    context.state.projectName = projectName;
  }

  after() {}
  rollback() {}
}

class LoadConfigStep implements PipelineStep {
  name = "Load Config";

  before() {
    Logger.info("Loading project configuration");
  }

  execute(context: WorkflowContext) {
    context.state.config = { loaded: true };
  }

  after() {}
  rollback() {}
}

class LoadPluginsStep implements PipelineStep {
  name = "Load Plugins";

  before() {
    Logger.info("Loading plugins");
  }

  execute(context: WorkflowContext) {
    const manager = new PluginManager(context.config.pluginRoot);
    context.state.plugins = manager.loadAll().map((plugin) => plugin.manifest);
  }

  after() {}
  rollback() {}
}

class LoadTemplateStep implements PipelineStep {
  name = "Load Template";

  before() {
    Logger.info("Loading template spec");
  }

  execute(context: WorkflowContext) {
    const engine = new TemplateEngine(context.config.templateRoot);
    const templateName = context.state.templateName ?? "";
    const errors = engine.validate(templateName);

    if (errors.length > 0) {
      throw new Error(errors.join("; "));
    }

    const spec = engine.load(templateName);
    if (!spec) {
      throw new Error(`Template ${templateName} not found`);
    }

    context.state.templateSpec = spec;
  }

  after() {}
  rollback() {}
}

class GenerateFilesStep implements PipelineStep {
  name = "Generate Files";

  before() {
    Logger.info("Generating project files");
  }

  execute(context: WorkflowContext) {
    const projectName = context.state.projectName ?? "";
    const targetRoot = path.join(context.config.projectRoot, projectName);
    context.state.generatedPaths.push(targetRoot);
  }

  after() {}
  rollback(context: WorkflowContext) {
    Logger.warn("Rollback: removing generated files");
    for (const generatedPath of context.state.generatedPaths) {
      if (generatedPath) {
        try {
          if (fs.existsSync(generatedPath)) {
            fs.rmSync(generatedPath, { recursive: true, force: true });
          }
        } catch {
          Logger.warn(`Could not remove ${generatedPath}`);
        }
      }
    }
  }
}

class ReplaceVariablesStep implements PipelineStep {
  name = "Replace Variables";

  before() {
    Logger.info("Replacing template variables");
  }

  execute(context: WorkflowContext) {
    const engine = new TemplateEngine(context.config.templateRoot);
    const templateName = context.state.templateName ?? "";
    const variables = {
      PROJECT_NAME: context.state.projectName ?? "",
      AUTHOR: "KORAVA",
      DATE: new Date().toISOString(),
      VERSION: "1.0.0",
      DESCRIPTION: "Generated by KORAVA Builder"
    };

    context.state.renderedFiles = engine.render(templateName, variables);
    const targetRoot = path.join(context.config.projectRoot, context.state.projectName ?? "");
    for (const file of context.state.renderedFiles) {
      const filePath = path.join(targetRoot, file.relativePath);
      context.state.generatedPaths.push(filePath);
    }
  }

  after() {}
  rollback() {}
}

class ValidateOutputStep implements PipelineStep {
  name = "Validate Output";

  before() {
    Logger.info("Validating generated output");
  }

  execute(context: WorkflowContext) {
    if (context.state.renderedFiles.length === 0) {
      throw new Error("No files were rendered");
    }
  }

  after() {}
  rollback() {}
}

class SuccessStep implements PipelineStep {
  name = "Success";

  before() {
    Logger.info("Finalizing workflow");
  }

  execute(context: WorkflowContext) {
    Logger.success(`Workflow completed for ${context.state.projectName}`);
  }

  after() {}
  rollback() {}
}
