import { Command } from "../core/registry.js";
import * as path from "path";
import { TemplateEngine } from "../templates/engine.js";
import { Logger } from "../core/logger.js";

const supportedTemplates = ["agent", "website", "saas", "bim"];

const variables = (projectName: string) => ({
  PROJECT_NAME: projectName,
  AUTHOR: "KORAVA Builder",
  DATE: new Date().toISOString().split("T")[0],
  VERSION: "0.1.0",
  DESCRIPTION: "Generated by KORAVA Builder"
});

export const newCommand: Command = {
  name: "new",
  aliases: ["create"],
  description: "Create a new project from a KORAVA template",
  run(args: string[]) {
    const templateType = args[0];
    const projectName = args[1];

    if (!templateType || !projectName) {
      Logger.error("Usage: new <template> <project-name>");
      Logger.info("Supported templates:", supportedTemplates.join(", "));
      return 1;
    }

    if (!supportedTemplates.includes(templateType)) {
      Logger.error(`Unknown template type: ${templateType}`);
      Logger.info("Supported templates:", supportedTemplates.join(", "));
      return 1;
    }

    const templateRoot = path.resolve(process.cwd(), "templates");
    const engine = new TemplateEngine(templateRoot);

    Logger.info("Loading template", templateType);
    const loadErrors = engine.validate(templateType);
    if (loadErrors.length > 0) {
      Logger.error("Template validation failed:");
      loadErrors.forEach((error) => Logger.error(error));
      Logger.info("Available templates:", supportedTemplates.join(", "));
      return 1;
    }

    const targetRoot = path.resolve(process.cwd(), "projects", projectName);
    if (path.isAbsolute(templateType) || templateType.includes("..")) {
      Logger.error("Invalid template name.");
      return 1;
    }

    Logger.info("Creating project", targetRoot);
    engine.copy(templateType, targetRoot, variables(projectName));

    Logger.info("Replacing variables");
    Logger.success(`Created project ${projectName} from template ${templateType}`);
    Logger.success("Done");
    return 0;
  }
};
