import { TemplateVariableSet } from "../../templates/types.js";

export function buildProjectVariables(projectName: string): TemplateVariableSet {
  return {
    PROJECT_NAME: projectName,
    AUTHOR: "KORAVA Builder",
    DATE: new Date().toISOString().split("T")[0],
    VERSION: "0.1.0",
    DESCRIPTION: "Generated by KORAVA Builder"
  };
}
